### ISSUE TITLE
consume multiple chars edge case

### ISSUE THREAD

**Issue by Caesurus** [sirkon/ldetool#21]
thank you for adding the `*'c'` rule, i think i found an edge case though:
If i have a lde rule like this
LDERule1 = 
*' ' Val1      (int) " |"
*' ' Val2      (int) " |"
;

the resulting code:
```
	// Pass all characters ' ' at the rest start
	for headPassCounter, headPassValue = range string(p.Rest) {
		if headPassValue != ' ' {
			break
		}
	}
	if headPassCounter > 0 {
		p.Rest = p.Rest[headPassCounter:]
	}

	// Take until " |" as Val1(int)
	pos = strings.Index(p.Rest, spaceBar)
	if pos >= 0 {
		tmp = p.Rest[:pos]
		p.Rest = p.Rest[pos+len(spaceBar):]
	} else {
		return false, nil
	}
	if tmpInt, err = strconv.ParseInt(tmp, 10, 64); err != nil {
		return false, fmt.Errorf("cannot parse `%s` into field Val1(int): %s", tmp, err)
	}
	p.Val1 = int(tmpInt)

	// Pass all characters ' ' at the rest start
	for headPassCounter, headPassValue = range string(p.Rest) {
		if headPassValue != ' ' {
			break
		}
	}
	if headPassCounter > 0 {
		p.Rest = p.Rest[headPassCounter:]
	}
```
The problem come in when you test a line like: "     3 |"
The second time it looks for the spaces to pass, it will do:
`for headPassCounter, headPassValue = range string(p.Rest) {`
but since there is no more characters in p.Rest it will not set `headPassCounter` to zero, it will maintain the previous count.

So the following ends up being larger than 0, and results in a panic.
```
	if headPassCounter > 0 {
		p.Rest = p.Rest[headPassCounter:]
	}
```

Setting `headPassCounter` to 0 before doing the range fixes the panic. I will try to fork, make a change and issue a pull request. But figured it would be good to outline the issue here.

**Comment by sirkon** [comment]
Hi!

Interesting, I am looking for the PR!

**Comment by Caesurus** [comment]
I created the PR, I picked clearing the variable before each usage. I updated the unit test as well.

**Comment by sirkon** [comment]
Thank you!
Done
