### ISSUE TITLE
Ignoring unicode prefix

### ISSUE THREAD

**Issue by hookenz** [sirkon/ldetool#27]
At the start of the log file I have:

    ï»¿*** Time: 2/1/2019 12:10:17

But only on the first line.
Subsequently, the first line does not match with this rule

    Timestamp = 
        ^"*** Time: " Time(string);

How do I write an appropriate rule to ignore those unicode related characters (ï»¿) ?

**Comment by sirkon** [comment]
This should work

```
Timestamp = (^"ï»¿")  ^"*** Time: " Time(string);
```

Update ldetool though, there was a bug in dependencies.

PS I would pass the first line manually, but the proposed rule should be fast enough anyway.

**Comment by sirkon** [comment]
fixed
