### ISSUE TITLE
Call arbitrary function on match/conversion

### ISSUE THREAD

**Issue by hookenz** [sirkon/ldetool#28]
A great feature would be to support custom types.  e.g. time.

For example, instead of:

    Rule = Time(string) 

Have:

    Rule = Time(time.Time)  // time.Time = go type

Then expect the user to write the function to decode it

    func (p *Rule) UnmarshalTime(field byte[]) (time.Time, err) {

    }

or  what about if the input is a string, but we do some special decoding to convert it to an int

    Rule = PumpState(int)

    func (p *Rule) UnmarshallPumpState(field byte[]) (int, err) {
   
    }

Perhaps the unmarshaller is somehow optional.  Just some things to ponder.

**Comment by sirkon** [comment]
It looks like a great idea. 

It will not work in form suggested though: types need to be exported, import path is needed.

So, we need to specify it.

I guess this will be a good way:

```
type time.Time from "time";
type customType; // defined in the current package
```

And once field's type is not a built in one it will be looked in these declared types and the `UnmarshalField` will be generated if found.

**Comment by hookenz** [comment]
A time field would require Unmarshalling because a time string has many possible formats.

e.g.

    func (p *Rule) UnmarshalTime(field byte[]) (time.Time, err) {
        return time.Parse("2005-01-02 15:04:00.000", string(field));
    }

**Comment by sirkon** [comment]
Implemented. Unmarshal functions made private though. Check it out.

**Comment by sirkon** [comment]
Also, about dispatching (you asked for it in another issue I closed).

Using

```
Rule = ?Alt1(…) ?Alt2(…) …;
```

For dispatching is a wrong pattern. I said in that issue decoding errors causes error return. I am long out of this stuff (data processing) so forgot the reason behind this. Recalled it though:

Imagine we have a line

```
2019-07-20T15:32:39.123+03:00 Duration:91 Provider:Deutche Telekom Activity:Call …
2019-07-20T15:32:39.138+03:00 Provider:Vodafon Activity:SMS …
```
And a rule to decompose it.

```
type time.Time from "time"; // :)

Rule = Time(time.Time) ' ' ?Duration(^"Duration:" Value(uint) ~' ') ^"Provider:" Provider(string) ' ' ^"Activity:" Activity(string) ' ';
```

What if Duration value will not be a correct number? Obviously, this thing must be spotted and reported. If we would have silent returns from optional areas we would pass it. Encoding was made loud for this reason exactly. 

PS I guess so called "silent optional areas" could be introduced for dispatching purposes, something like that:

```
Rule = ??Alt1(…) ??Alt2(…) …;
```

Need a bit of work though. Code of code generator is horrible, need to rewrite it.

**Comment by sirkon** [comment]
Well, added custom unmarshalers for builtin types.

Use `$int` instead of `int` to use custom `unmarshal<Field>` function. `hex`, `oct`, `dec` types are not supported for this notation – a user will be asked to change `hex` and `oct` into respective `int` and use custom types for `dec` (they are tricky and only exists because [Clickhouse](https://clickhouse.yandex) supports them – this utility grew from the need to feed it).

Also, `bool` type partial support was added – will work via custom parsing function.

**Comment by sirkon** [comment]
Done
