### ISSUE TITLE
[Feature Request] JSON tags 

### ISSUE THREAD

**Issue by TuSKan** [sirkon/ldetool#34]
Hi,

Would be very helpful a options to write JSON tags on the generated structures.

```
// Line autogenerated parser
type Line struct {
    Rest   []byte         `json:"rest"
    Time   []byte        `json:"time"
    First  uint8           `json:"first"
    Format []byte      `json:"format"
    Hidden struct {
        Valid bool
        Value uint8     `json:"value,omitempty"
    }   `json:"hidden,omitempty"
    UserAgent []byte `json:"user_agent"
    Country   []byte   `json:"country"
}
```

**Comment by sirkon** [comment]
Frankly, I am not sure if this is a right place for this kind of functionality. An ability to use this structure for output (which is what these tags are needed for) looks to be a lucky coincidence. 

Please, describe the case/set of cases you need these tags for.

**Comment by sirkon** [comment]
@TuSKan?

**Comment by TuSKan** [comment]
Its just to save a file from the parsed struct.
It's not really necessary.

**Comment by sirkon** [comment]
Got it, thank you.

`omitempty` will not work well: https://play.golang.org/p/ZD2ZrJECau2

And, the most important, this structure does not represent the final value typically, it still needs additional processing in most cases, at least it was for me (when I was using the prototype of this tool). And it is not hard to write a small utility which will add tags for structures declared in a file anyway.
