### ISSUE TITLE
Support comments for types and type fields

### ISSUE THREAD

**Issue by vitalyisaev2** [sirkon/ldetool#35]
It would be nice to have opportunity to define comments on types and type fields to make them appear in generated code.

`diskstats.lde`:

```
// Disk usage statistics provided by Linux kernel prior to 4.19
DiskstatsBefore419 =
    *' '
    // Major device number
    Major(uint16) ~' '
    *' '
    // Minor device number
    Minor(uint16) ~' '
    // Device name
    Device(str) ' '
    // Read operations happened since system boot
    ReadIOs(uint32) ' '

```

results in `diskstats.go`:
```go
    // Disk usage statistics provided by Linux kernel prior to 4.19
    type DiskstatsBefore419 struct {
        // Major device number
        Major uint16
        // Minor device number
        Minor uint16
        // Device name
        Device string
        // Read operations happened since system boot
        ReadIOs uint32
    }
```

**Comment by sirkon** [comment]
This is a good idea.

They better be golint-compliant, I mean `golint` will not be particularly happy about the first comment and this is not good as the code should be readable and editable by humans. This means a comment for types and fields should start with an entity name:

```perl
# DiskstatsBefore419 usage statistics provided by Linux kernel prior to 4.19
DiskstatsBefore419 =
    *' '
    # Major device number
    Major(uint16) ~' '
    *' '
    # Minor device number
    Minor(uint16) ~' '
    # Device name
    Device(str) ' '
    # ReadIOs read operations happened since system boot
    ReadIOs(uint32) ' '
```

So, what is the proposal: if a given line starts with 

* Rule definition
* Optional named area definition
* Field definition

at a certain offset and it has a comment block (one or more comment lines right before the element aligned with current line horizontally ≡ having the same offset) started with current entity name, then it is considered to be a commentary for current item and would be consumed as a commentary for the item in the source code to be generated.

So, this 

```perl
# Commentary
Rule = 
    # Item comment
    Item(string);
```

will produce

```go
type Rule struct {
    // Item comment
    Item string
}
```

and this

```perl
# Rule commentary
Rule = 
    # Item comment
    Item(string);
```

will do

```go
// Rule commentary
type Rule struct {
    // Item comment
    Item string
}
```

**Comment by sirkon** [comment]
Dropped the "starts with the rule or field name" constraint, each comment block aligned with current entity (rule or take block) will be translated into an respective entity's comment.

**Comment by sirkon** [comment]
Done. Feel free to report on wrong comment transition.

**Comment by sirkon** [comment]
Just made comment consumption more liberal. Now, this will work as well

```perl
# Rule rule
Rule = 
    # Field filed
    _"field[" Field(string) ']'
    # Value value
    ^" value[" Value(string) '];
```

I.e. the first of a line taker gets comments above line aligned with this line' start.
