### ISSUE TITLE
.\ldetool.go:59:12: undefined: generateAction

### ISSUE THREAD

**Issue by jiebanghan** [sirkon/ldetool#4]
I go get all the project ldetool, and then I run the command go build  ldetool.go , it shows me .\ldetool.go:59:12: undefined: generateAction
please tell me how to solve it? My aim is to debug ldetool in goland, so I build it from source.

**Comment by sirkon** [comment]
`go get` alone is enough. `ldetool` executable should be in a `$GOPATH/bin` (or in `$HOME/go/bin` after it, no need to run `go build` at all.

**Comment by jiebanghan** [comment]
Thank you. But my aim is to debug ldetool in goland for study, so I build it from source. I want to set some breakpoints in source, so I want to build it myself. How to solve the problem?thank you.

**Comment by sirkon** [comment]
Updated my answer, you need to change run configuration setup.

**Comment by jiebanghan** [comment]
thank you very much . you are so nice for answering a newer's question.thank you very much .

**Comment by sirkon** [comment]
Not actually ldetool issue, JetBrains UX designers should rework their approaches.
