### ISSUE TITLE
Invalid code generation with nested optional blocks

### ISSUE THREAD

**Issue by traetox** [sirkon/ldetool#40]
The following lde definition generates invalid golang code:
```
FOOBARBAZ =
        ^"<foo>" Stuff(string) ^"</foo>"
        ?Bar ( ^"<Bar" ?ID (^" foobar='{" Foobarbaz(string) "}'") ^"/>" )
        ^"<baz>" Baz(string) "</baz>"
;
```
It appears that the function that generates labels for goto operations is colliding.  This is the golang error:

```
./parser_lde.go:62:8: label foobarbazBarLabel not defined
./parser_lde.go:64:10: undefined: barRest
./parser_lde.go:85:2: undefined: barRest
./parser_lde.go:98:1: label foobarbazBarIDLabel already defined at ./parser_lde.go:86:1
```
Here is the lde tool output:
```
Rule `FOOBARBAZ`: processing
Check and pass "<foo>"
Take the rest as Stuff(string)
Check and pass "</foo>"
Named option Bar
Check and pass "<Bar"
Named option ID
Check and pass " foobar='{"
Take until "}'" as Foobarbaz(string)
End of named option ID
Check and pass "/>"
End of named option Bar
Check and pass "<baz>"
Take until "</baz>" as Baz(string)
Rule `FOOBARBAZ`: done
```

**Comment by sirkon** [comment]
Hi, thank you for the bug report.

Did you mean
```perl
FOOBARBAZ =
        ^"<foo>" Stuff(string) "</foo>"
        ?Bar ( ^"<Bar" ?ID (^" foobar='{" Foobarbaz(string) "}'") ^"/>" )
        ^"<baz>" Baz(string) "</baz>"
;
```
?
Because Stuff(string) without an anchor ('c' or "str") tells to capture everyting to the end and then `^"</foo>"` requires the rest (which is empty) starts with `"</foo>"`

**Comment by traetox** [comment]
You are correct, I tried to generate a concise example from a working system and fat fingered it.

Thank you for the update and feedback.

**Comment by sirkon** [comment]
done, please check it out

**Comment by sirkon** [comment]
Haven't you tried it?

**Comment by traetox** [comment]
Appears to be working great on ae961f55aecb462b8ec25d3e1950a9c1a7e2cd09


Thank you very much for all your work!
