### ISSUE TITLE
C version planned?

### ISSUE THREAD

**Issue by rofl0r** [sirkon/ldetool#43]
this is a really impressive tool.

unfortunately due to being written in go/emitting go it's restricted to be only used by go code, whereas if there was a C version of it it could be used by any PL that can interface to C libraries/code (i.e. almost any).

are there any plans to make it available to them ?

**Comment by sirkon** [comment]
Hi.

It is possible and I actually had it in mind (about other languages), but I am afraid I don’t have a time for this. Just too much work.

**Comment by rofl0r** [comment]
fair enough. i wish you the best in your endeavours.
